version: '2'

networks:
  network-spring-kafka-test:
    driver: bridge

services:
  kafka-server:
    image: 'bitnami/kafka:latest'
    networks:
      - network-spring-kafka-test
    ports:
      - "9094:9094"
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-server:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka-server:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=false
  init-kafka:
    image: 'bitnami/kafka:latest'
    depends_on:
      - kafka-server
    networks:
      - network-spring-kafka-test
    command: 
      - /bin/sh
      - -c
      - |
        sleep 10
        echo 'Inicializando configuração do Kafka'
        kafka-topics.sh --list --bootstrap-server kafka-server:9092 

        echo 'Creating kafka topics'
        kafka-topics.sh --create --if-not-exists --topic test-topic --partitions 3 --bootstrap-server kafka-server:9092
        kafka-topics.sh --create --if-not-exists --topic test-topic-annotation --partitions 3 --bootstrap-server kafka-server:9092

        echo 'Successfully created the following topics:'
        kafka-topics.sh --list --bootstrap-server kafka-server:9092
  spring-kafka-test-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: 'spring-kafka-test:latest'
    networks:
      - network-spring-kafka-test
    depends_on:
      - kafka-server
    deploy:
      mode: replicated
      replicas: 3